### ISSUE TITLE
Sub pages missing

### ISSUE THREAD

**Issue by aboger** [u2smile85/prawnporn#8]
Please add missing sub pages:

- Merchandise, showcasing T-Shirts, mugs, and so on
- Advertise, providing the possibility to advertise with us
- About, providing legal and information about the website. Some lorem ipsum should be fine.

**Comment by aboger** [comment]
You can spare out `About`, as we've already implemented one.

**Comment by aboger** [comment]
Any progress?

**Comment by u2smile85** [comment]
Added subpages please check it and give the feedback

**Comment by aboger** [comment]
The user dashboard has no content, please add.

**Comment by u2smile85** [comment]
> dashboard

user dashboard content added
